inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-performance

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable