name: Docker

on: [push,pull_request]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          tags: joel/weblog:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}